### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by noahsalvi** [r-bt/r-bt.com#2]
Hey Richard

I built a script that creates a sapper project and configures it so that you can deploy it on netlify with their serverless functions.
That way you won't need to export your project to static files and so on...
Maybe it could come in handy for your website? [sapper-netlify](https://github.com/noahsalvi/sapper-netlify#readme)

**Comment by noahsalvi** [comment]
Oh and I forgot, can I reference your "learning" about sotion in the readme or else where?

**Comment by r-bt** [comment]
Ohhh, this looks really cool. I'll try it out this weekend, moving to SSR would be much nicer. Thanks!

Yikes now I've got this and svelte-kit to look into :) 

Yep, of course you can reference it wherever you want
